server:
  port: 8080

spring:
  application:
    name: jlbatross
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:templates/,classpath:/static/

